=== AlexRandomed/jahia/war/src/main/webapp/WEB-INF/etc/xml_dtd/templates_2_0.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 
/*
 * Copyright 2002-2008 Jahia Ltd
 *
 * Licensed under the JAHIA COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (JCDDL), 
 * Version 1.0 (the "License"), or (at your option) any later version; you may 
 * not use this file except in compliance with the License. You should have 
 * received a copy of the License along with this program; if not, you may obtain 
 * a copy of the License at 
 *
 *  http://www.jahia.org/license/
 *
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License.
 */
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:jahia="http://www.jahia.net/jahia/templates" targetNamespace="http://www.jahia.net/jahia/templates" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0">
  <element name="template-set">
    <complexType>
      <sequence>
        <element name="package-name" type="string"/>
        <element name="extends" type="string" minOccurs="0"/>
        <element name="root-folder" type="string"/>
        <element name="initial-import" type="string" minOccurs="0"/>
        <element name="provider" type="string" minOccurs="0"/>
        <element name="thumbnail" type="string" minOccurs="0"/>
        <element name="description" type="string" minOccurs="0"/>
        <element name="resource-bundle" type="string" minOccurs="0"/>
        <element name="definitions-file" type="string" minOccurs="0" maxOccurs="unbounded"/>
        <element name="rules-file" type="string" minOccurs="0" maxOccurs="unbounded"/>
        <element name="common-pages" minOccurs="0">
          <complexType>
            <sequence>
              <element name="my-settings" type="string" minOccurs="0"/>
              <element name="my-settings-success" type="string" minOccurs="0"/>
              <element name="search-results" type="string" minOccurs="0"/>
            </sequence>
          </complexType>
        </element>
        <element name="properties" minOccurs="0">
          <complexType>
            <sequence>
              <element name="property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                  <attribute name="key" type="string" use="required"/>
                  <attribute name="value" type="string" use="required"/>
                </complexType>
              </element>
            </sequence>
            <attribute name="default" use="optional"/>
            <attribute name="homepage" use="optional"/>
          </complexType>
        </element>
        <element name="templates" minOccurs="0">
          <complexType>
            <sequence>
              <element name="template" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                  <attribute name="name" type="string" use="required"/>
                  <attribute name="display-name" type="string" use="optional"/>
                  <attribute name="filename" type="string" use="required"/>
                  <attribute name="visible" type="boolean" use="optional" default="true"/>
                  <attribute name="page-type" type="string" use="optional" />
                  <attribute name="description" type="string" use="optional"/>                  
                </complexType>
              </element>
            </sequence>
            <attribute name="default" use="optional"/>
            <attribute name="homepage" use="optional"/>
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>
</schema>

=== AlexRandomed/jahia/templates/social-templates/src/main/webapp/WEB-INF/templates.xml
<?xml version="1.0" encoding="UTF-8"?>

<template-set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.jahia.org/jahia/templates" xsi:schemaLocation="http://www.jahia.org/jahia/templates http://www.jahia.org/shemas/templates_2_0.xsd">
    <package-name>Social templates</package-name>
    <root-folder>social-templates</root-folder>
    <provider>http://www.jahia.org</provider>
    <thumbnail>images/preview.png</thumbnail>
    <resource-bundle>resources.SocialTemplates</resource-bundle>
    <definitions-file>definitions.cnd</definitions-file>
    <common-pages>
        <search-results>searchresult.jsp</search-results>
    </common-pages>
    <templates default="Blog" homepage="blog">
        <template name="Blog" display-name="template.name.blog" filename="tpl.blog.jsp" page-type="social_templates:blog" description="template.description.blog"/>
    </templates>
</template-set>
